--INSERIR TIMES
EXEC INSERIR_TIME_FUTEBOL 'PALMEIRAS', 'PAL'
EXEC INSERIR_TIME_FUTEBOL 'SAO PAULO', 'SAO'
EXEC INSERIR_TIME_FUTEBOL 'SANTOS', 'SAN'
EXEC INSERIR_TIME_FUTEBOL 'CORINTHIANS', 'COR'
EXEC INSERIR_TIME_FUTEBOL 'FERROVIARIA', 'FEO'


--SELECT * FROM TIME_FUTEBOL

EXEC INSERIR_CAMPEONATO 2000, 'PAULISTA'

--PARTIDA PALMEIRAS 
EXEC INSERIR_JOGO 'PALMEIRAS', 'SANTOS', 1
EXEC ATUALIZAR_GOLS 3,2,1
EXEC INSERIR_JOGO 'PALMEIRAS', 'CORINTHIANS', 1
EXEC ATUALIZAR_GOLS 2,2,2
EXEC INSERIR_JOGO 'PALMEIRAS', 'SAO PAULO', 1
EXEC ATUALIZAR_GOLS 1,2,3
EXEC INSERIR_JOGO 'PALMEIRAS', 'FERROVIARIA', 1
EXEC ATUALIZAR_GOLS 6,2,4
EXEC INSERIR_JOGO 'SANTOS','PALMEIRAS', 1
EXEC ATUALIZAR_GOLS 2,2,5
EXEC INSERIR_JOGO 'CORINTHIANS','PALMEIRAS', 1
EXEC ATUALIZAR_GOLS 2,2,6
EXEC INSERIR_JOGO 'SAO PAULO','PALMEIRAS', 1
EXEC ATUALIZAR_GOLS 1,2,7
EXEC INSERIR_JOGO 'FERROVIARIA','PALMEIRAS', 1
EXEC ATUALIZAR_GOLS 2,2,8

--PARTIDAS SANTOS
EXEC INSERIR_JOGO 'SANTOS', 'CORINTHIANS', 1
EXEC ATUALIZAR_GOLS 1,2,9
EXEC INSERIR_JOGO 'SANTOS', 'SAO PAULO', 1
EXEC ATUALIZAR_GOLS 4,2,10
EXEC INSERIR_JOGO 'SANTOS', 'FERROVIARIA', 1
EXEC ATUALIZAR_GOLS 3,3,11
EXEC INSERIR_JOGO 'CORINTHIANS','SANTOS', 1
EXEC ATUALIZAR_GOLS 4,2,12
EXEC INSERIR_JOGO 'SAO PAULO','SANTOS', 1
EXEC ATUALIZAR_GOLS 3,1,13
EXEC INSERIR_JOGO 'FERROVIARIA','SANTOS', 1
EXEC ATUALIZAR_GOLS 3,0,14

--PARTIDAS CORINTHIAS
EXEC INSERIR_JOGO 'CORINTHIANS', 'SAO PAULO', 1
EXEC ATUALIZAR_GOLS 2,3,15
EXEC INSERIR_JOGO 'CORINTHIANS', 'FERROVIARIA', 1
EXEC ATUALIZAR_GOLS 1,3,16
EXEC INSERIR_JOGO 'SAO PAULO','CORINTHIANS', 1
EXEC ATUALIZAR_GOLS 0,0,17
EXEC INSERIR_JOGO 'FERROVIARIA','CORINTHIANS', 1
EXEC ATUALIZAR_GOLS 1,0,18


--PARTIDAS SAO PAULO 
EXEC INSERIR_JOGO 'SAO PAULO','FERROVIARIA', 1
EXEC ATUALIZAR_GOLS 0,2,19 
EXEC INSERIR_JOGO 'FERROVIARIA','SAO PAULO', 1
EXEC ATUALIZAR_GOLS 1,1,20


SELECT * FROM JOGO
SELECT * FROM TIME_FUTEBOL



--ATUALIZAR VENCEDOR 
EXEC BUSCAR_VENCEDOR_CAMPEONATO
EXEC ATUALIZAR_VENCEDOR 'FERROVIARIA',1

SELECT * FROM CAMPEONATO